# Site settings
title: UMSTeK
email: umstek@live.com
description: > # ignore newlines until "baseurl:"
   Copyright © 2006-2016 by Wickramaranga Abeygunawardhana. <br>
   Website built with Jekyll using Visual Studio Code and Atom on elementary OS 0.4 Loki,
   hosted on github-pages.
baseurl: ""
url: "http://umstek.github.io"

# Build settings
collections: # cheatsheets
  qref:
    output: true
    permalink: /cheatsheets/:path

markdown: kramdown
gems:
  - jemoji
  - jekyll-seo-tag
  - jekyll-github-metadata
sass:
  style: :compressed
permalink: /blog/:year/:month/:day/:title
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Readme.md
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "qref"
