name: prod-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Configure Git
        run: |
          git config --global user.email "w@umstek.tk"
          git config --global user.name "Wickramaranga Abeygunawardhana"
      - name: Deploy Gatsby site
        run: yarn deploy
