name: prod-deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build project
        run: yarn build
      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: public/
          if-no-files-found: error
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps: 
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: Configure git
        run: |
          git config --global user.email "w@umstek.tk"
          git config --global user.name "Wickramaranga Abeygunawardhana"
          git init
